### PR TITLE
fix can't see tables when use named database

### PR DESCRIPTION
**Pull request by CYRUS-STUDIO**
fix realm database is empty when use named database.

img

### CODE REVIEW

**Comment by Delphian2015** [comment]
linchaolong, how can I update this in my project?

**Comment by CYRUS-STUDIO** [comment]
clone [this project](https://github.com/linchaolong/stetho-realm)
1. [Create aar file in Android Studio](http://stackoverflow.com/questions/24309950/create-aar-file-in-android-studio), and copy the aar file to libs dir.

2. import aar 
```
repositories{
  flatDir{
    dirs 'libs'
  }
}
dependencies {
  compile(name:'stetho_realm-release', ext:'aar')
}
```

**Comment by Delphian2015** [comment]
Thank you. I will try to do it!

**Comment by JamesMcIntosh** [comment]
Hi Makoto, @zaki50 

Could you please review this pull request and #48 as they are both very small fixes which unblock people using this project as currently this project is broken if you have more than one realm.

Many thanks
James McIntosh

**Comment by zaki50** [comment]
Thank you so much to make a PR to fix the bug.
I fixed the bug and released 2.1.0 that contains the fix.

This PR helped me a lot!

**Pull request closed without merging**
